<img src="img/numpy-logo.png" width="100" height="100" align="center"/>

## What is NumPy  

NumPy or Numeric Python is the fundamental package for scientific computing with Python. It is a Python library that acts as a wrapper around underlying C and Fortran code. NumPy focuses on matrices, which are called in the arrays. It contains among other things:
- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

***

### NumPy Resources
*https://docs.scipy.org/doc/numpy/about.html?highlight=numpy%20random*
*https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html*
*https://docs.scipy.org/doc/numpy/*
*https://metaspace.blog/programming/python/python-numpy-basics-2*
*https://www.quora.com/In-Python-what-is-NumPy-How-is-it-used*
*https://docs.scipy.org/doc/numpy-1.15.1/reference/ufuncs.html*

***

### Examples

There are some limitations in using the Python list and NumPy provides an alternative to the regular Python list. We can analyze data much more efficiently and perform calculations over entire arrays. 

In [1]:
# an example of standard Pyhon lists
list_a = [1, 2, 3, 4, 5]
list_b = [5, 4, 3, 2, 1]
result = []

for i in range(0, len(list_a)):
    result.append(list_a[i] * list_b[i])
print(result)

In [2]:
# an example of NumPy's arrays
import numpy as np

list_a = np.array([1, 2, 3, 4, 5])
list_b = np.array([5, 4, 3, 2, 1])
print(list_a * list_b)

[5 8 9 8 5]


In [3]:
# arranging and reshaping array using NumPy's built in functions
x = np.arange(24).reshape(2,3,4)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


## What is MathLib

In [4]:
import matplotlib.pyplot as plt

## Random module - Generate pseudorandom numbers
Random is a module that implements pseudorandom number generators for various distributions. NumPy has its own implementation of a random generator and as well as Python also implements the Mersenne Twister pseudorandom number generator. 

## numpy.random.random() and numpy.random.rand() functions

Both random.random and random.rand functions generate pseudo random floating point samples from the uniform distribution in the range [0.0, 1.0). It means that generated samples will include 0.0, but not include 1.0, which is also known as a semi-open range or half-closed interval / half-open interval range.

[Mathworld](http://mathworld.wolfram.com/Half-ClosedInterval.html) eplains it as an interval in which one endpoint is included but not the other. A half-closed interval is denoted [a,b) or (a,b] and is also called a half-open interval.

![half-closed-interval](img/halfClosedInterval.png)

* **numpy.random.random()** function
returns random floats in the half-open interval [0.0, 1.0). It is actually an alias for numpy.random.random_sample() funtion.
[Results](https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.random.html#numpy.random.random) are from the "continuous uniform" distribution over the stated interval. Random.random() takes only one argument, the shape argument is a single tuple


In [5]:
# Generate random float number in the range [0.0, 1.0)
num = np.random.random()
print(num)

0.8032218383304246


In [6]:
# If argument is given, for ex. 4, it will generate four random floats in the range [0.0, 1.0)
num = np.random.random(4)
print(num)

[0.88935365 0.0843956  0.875113   0.61849006]
